### ISSUE TITLE
Add Interactive mind map for better understanding.

### ISSUE THREAD

**Issue by abisekhsubedi** [whoissubedibibek/fullstackResources#1]
Software development isn't a linear process, we would not spend our entire life just learning but learning what is enough and improving every day.

A clear and concise interactive mind map for understanding the flow.

Check: [roadmap.sh](https://roadmap.sh/)

**Comment by whoissubedibibek** [comment]
yup I totally agree with you, I've seen people who waste all the day searching for resources to learn so this repo contains pdfs and video and blog content to get started with, that's all .
